### ISSUE TITLE
Occasional error with `java -jar target/task-1.0-SNAPSHOT.jar`

### ISSUE THREAD

**Issue by rfelcman** [dalexandrov/task#2]
Command "java -jar target/task-1.0-SNAPSHOT.jar" sometimes doesn't work. It seems, that client/consumer is sometimes started sooner, than server.

**Comment by dalexandrov** [comment]
Please review https://github.com/dalexandrov/task/commit/8804d4ee21179952e3f13090c658b7f70f7ccaa8
