### ISSUE TITLE
Dosn't work on old computers! :)

### ISSUE THREAD

**Issue by danielkec** [dalexandrov/task#4]
I believe that when `Runtime.getRuntime().availableProcessors()` return less than 4 `IllegalArgumentException` will be thrown.
https://github.com/dalexandrov/task/blob/master/src/main/java/local/mitia/combiner/TickerClientCombiner.java#L135-L139

**Comment by dalexandrov** [comment]
Please review https://github.com/dalexandrov/task/commit/ec4e83d42dd0e344fff1957ee947f0a53a7090b8

**Comment by dalexandrov** [comment]
Minor changes done. Please review https://github.com/dalexandrov/task/commit/671290f6d07fab346b411b704ce8bfe5b4e600eb
Trying not to overcomplicate thelogic.

**Comment by danielkec** [comment]
Fixed by ec4e83d and 671290f
