### ISSUE TITLE
New JAXBContext and Unmarshaller is created in every loop

### ISSUE THREAD

**Issue by rfelcman** [dalexandrov/task#5]
New JAXBContext and Unmarshaller is created in every loop. Is it necessary? Maybe there is space for performance improvement.

**Comment by dalexandrov** [comment]
Ah yes.. stupid stuff from my side..

**Comment by dalexandrov** [comment]
Please review https://github.com/dalexandrov/task/commit/6a76037889aa4c0e3c49f17b7eb211cb0b7b20d4
