### ISSUE TITLE
Unnecessary synchronization

### ISSUE THREAD

**Issue by danielkec** [dalexandrov/task#7]
May have overseen something but I believe synchronization block is not needed as `local.mitia.combiner.TickerClientCombiner#getNextBatch` is always called from the same busy waiting thread.
https://github.com/dalexandrov/task/blob/master/src/main/java/local/mitia/combiner/TickerClientCombiner.java#L227

**Comment by dalexandrov** [comment]
I'll be quite honest, but I was not sure about this place exactly, I don't have much experience with concurrent collections. After a lot of reading, I have secured myself with this synchronisation. But, please, correct me if I'm wrong.

**Comment by danielkec** [comment]
`ConcurrentLinkedQueue`'s `poll` and `offer` are atomic operations thx to CAS used internally. Funny thing is this synchronized block shouldn't influence performance as escape analysis is going to identify unused lock and execute lock elision on it.

**Comment by danielkec** [comment]
Fixed by 2d7dfe0
